# Generated by Django 2.2.6 on 2019-10-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeclassroom', '0002_auto_20191021_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='student',
            new_name='students',
        ),
    ]
