# Generated by Django 2.2.4 on 2019-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclassroom', '0003_auto_20191021_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
